/** Declaration file generated by dts-gen */

export function listPrinter(language?: string): Promise<Array<string>>;

export function printFiles(pdfFiles: any[], printerName?: string, execPath?: string): Promise<boolean>;


