/** Declaration file generated by dts-gen */

export function listPrinter(pdfFiles: any[], printerName: string, execPath: string): Promise<boolean>;

export function printFiles(language = 'en-US'): Promise<Array<string>>;

